# Generated by Django 4.2.1 on 2023-06-06 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_npt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('otro', 'Otro')], default='mujer', max_length=10)),
                ('fecha_nacimiento', models.DateField(help_text='Enter date in MM-DD-YY format')),
                ('direccion', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=50)),
                ('provincia', models.CharField(choices=[('Buenos Aires', 'Buenos Aires'), ('Córdoba', 'Córdoba'), ('Santa Fe', 'Santa Fe')], default='Mendoza', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('comentarios', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ganancias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comentarios', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('monto_servicio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comentarios', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('producto', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comentarios', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cliente')),
            ],
        ),
        migrations.RemoveField(
            model_name='contract',
            name='company',
        ),
        migrations.RemoveField(
            model_name='npt',
            name='company',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='NPT',
        ),
        migrations.DeleteModel(
            name='Revenue',
        ),
    ]
